[0m16:11:27.876276 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0609A9E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E06152A360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E06152A8D0>]}


============================== 16:11:27.884276 | 030c3cac-270c-445d-8317-7337cb39f1d2 ==============================
[0m16:11:27.884276 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:11:27.885282 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\P15\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init snowflake_data_project', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:11:27.909626 [debug] [MainThread]: Starter project path: C:\Users\P15\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m16:11:27.929577 [info ] [MainThread]: 
Your new dbt project "snowflake_data_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:11:27.930589 [info ] [MainThread]: Setting up your profile.
[0m16:33:29.521279 [info ] [MainThread]: Profile snowflake_data_project written to C:\Users\P15\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:33:29.523262 [debug] [MainThread]: Command `dbt init` succeeded at 16:33:29.523262 after 1321.78 seconds
[0m16:33:29.524262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0609A9E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0023B67B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002E0013F5BB0>]}
[0m16:33:29.525279 [debug] [MainThread]: Flushing usage events
[0m16:33:30.455403 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:49:25.656565 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB82525610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB809A56D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB83099970>]}


============================== 22:49:25.661491 | a7768550-788d-4dd5-8fd6-f651c9a8f987 ==============================
[0m22:49:25.661491 [info ] [MainThread]: Running with dbt=1.9.2
[0m22:49:25.661491 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\P15\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:49:25.663114 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\P15\Desktop\Finance_Project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:49:25.663114 [debug] [MainThread]: Command `dbt run` failed at 22:49:25.663114 after 0.16 seconds
[0m22:49:25.664687 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB829482C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001ABFFF4F380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001AB833466F0>]}
[0m22:49:25.664687 [debug] [MainThread]: Flushing usage events
[0m22:49:26.470889 [debug] [MainThread]: An error was encountered while trying to flush usage events
